server:
  port: 8080

spring:
  application:
    name: api-gateway

  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
      registerWithEureka: true
      fetchRegistry: true

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: newsPortal-service
          uri: lb://newsPortal-service
          predicates:
            - Path=/api/v1/news/**
